/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seden0957
 */
public class JFrame8 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame8
     */
    public JFrame8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        slideOne = new javax.swing.JButton();
        slideTwo = new javax.swing.JButton();
        slideThree = new javax.swing.JButton();
        slideFour = new javax.swing.JButton();
        slideFive = new javax.swing.JButton();
        slideSix = new javax.swing.JButton();
        slideSeven = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayPanel.setBackground(new java.awt.Color(204, 0, 51));

        slideOne.setText("Slide 1");
        slideOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideOneActionPerformed(evt);
            }
        });

        slideTwo.setText("Slide 2");
        slideTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideTwoActionPerformed(evt);
            }
        });

        slideThree.setText("Slide 3");
        slideThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideThreeActionPerformed(evt);
            }
        });

        slideFour.setText("Slide 4");
        slideFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideFourActionPerformed(evt);
            }
        });

        slideFive.setText("Slide 5");
        slideFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideFiveActionPerformed(evt);
            }
        });

        slideSix.setText("Slide 6");
        slideSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideSixActionPerformed(evt);
            }
        });

        slideSeven.setText("Slide 7");
        slideSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideSevenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slideFour)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addComponent(slideFive)
                        .addGap(18, 18, 18)
                        .addComponent(slideSix))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, displayPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(slideOne)
                        .addGap(18, 18, 18)
                        .addComponent(slideTwo)))
                .addGap(18, 18, 18)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slideThree)
                    .addComponent(slideSeven))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slideOne)
                    .addComponent(slideTwo)
                    .addComponent(slideThree))
                .addGap(26, 26, 26)
                .addComponent(slideFour)
                .addGap(27, 27, 27)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slideFive)
                    .addComponent(slideSix)
                    .addComponent(slideSeven))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slideOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideOneActionPerformed
        this.setVisible(false);
        new JFrame1().setVisible(true);//goes back to the first slide
    }//GEN-LAST:event_slideOneActionPerformed

    private void slideTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideTwoActionPerformed
        this.setVisible(false);
        new JFrame2().setVisible(true); //goesd to slide 2 
    }//GEN-LAST:event_slideTwoActionPerformed

    private void slideThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideThreeActionPerformed
       this.setVisible(false);
        new JFrame3().setVisible(true); //goes to slide 3 
    }//GEN-LAST:event_slideThreeActionPerformed

    private void slideFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideFourActionPerformed
        this.setVisible(false);
        new JFrame4().setVisible(true); //goes to slide 4 
    }//GEN-LAST:event_slideFourActionPerformed

    private void slideFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideFiveActionPerformed
        this.setVisible(false);
        new JFrame5().setVisible(true);// goes to slide 5
    }//GEN-LAST:event_slideFiveActionPerformed

    private void slideSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideSixActionPerformed
        this.setVisible(false);
        new JFrame6().setVisible(true);// go back to slide 6 
    }//GEN-LAST:event_slideSixActionPerformed

    private void slideSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideSevenActionPerformed
        this.setVisible(false);
        new JFrame7().setVisible(true);//go back to slide seven
    }//GEN-LAST:event_slideSevenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton slideFive;
    private javax.swing.JButton slideFour;
    private javax.swing.JButton slideOne;
    private javax.swing.JButton slideSeven;
    private javax.swing.JButton slideSix;
    private javax.swing.JButton slideThree;
    private javax.swing.JButton slideTwo;
    // End of variables declaration//GEN-END:variables
}
